"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerPlugin = void 0;
const lexdef_commonmark_1 = require("./lexdef.commonmark");
const blockquote_1 = require("./blockquote");
const code_1 = require("./code");
const header_1 = require("./header");
const horizontal_rule_1 = require("./horizontal-rule");
const linkref_paragraph_1 = require("./linkref-paragraph");
const list_1 = require("./list");
const table_1 = require("./table");
const paragraph_1 = require("./paragraph");
const bold_italic_1 = require("./inline/bold-italic");
const code_2 = require("./inline/code");
const strike_1 = require("./inline/strike");
const link_1 = require("./inline/link");
const html_1 = require("./html");
const html_tag_1 = require("./inline/html-tag");
exports.registerPlugin = (processor, opts) => {
    lexdef_commonmark_1.addToLexer(processor.getLexer(), true);
    const bm = processor.getBlockManager();
    bm.addHandler(new html_1.HtmlBlockHandler());
    bm.addHandler(new blockquote_1.BlockquoteHandler());
    bm.addHandler(new code_1.CodeHandler());
    bm.addHandler(new header_1.HeaderHandler());
    bm.addHandler(new horizontal_rule_1.HorizontalRuleHandler());
    bm.addHandler(new linkref_paragraph_1.LinkrefParagraphHandler());
    bm.addHandler(new list_1.ListHandler());
    bm.addHandler(new code_1.CodeIndentedHandler());
    bm.addHandler(new table_1.TableHandler());
    bm.addHandler(new paragraph_1.ParagraphHandler());
    const im = processor.getInlineManager();
    im.addHandler(new html_tag_1.HtmlTagHandler());
    im.addHandler(new bold_italic_1.BoldHandler());
    im.addHandler(new bold_italic_1.ItalicHandler());
    im.addHandler(new bold_italic_1.StrongHandler());
    im.addHandler(new bold_italic_1.EmphasisHandler());
    im.addHandler(new code_2.CodeHandler());
    im.addHandler(new strike_1.StrikeHandler());
    im.addHandler(new link_1.LinkHandler());
    im.addHandler(new link_1.ImageHandler());
};
